%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/joao/Documents/MATLAB/Football/Doodle.xls
%    Worksheet: Poll
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/05/27 15:59:46

%% Import the data
function Doodle=import_doodle(fname)
[~, ~, Doodle] = xlsread(['/home/joao/Documents/MATLAB/Football/',fname],'Poll');
Doodle = Doodle(7:end-3,:);

Doodle = string(Doodle);
Doodle(ismissing(Doodle)) = '';
Doodle(:,2:end)=double(Doodle(:,2:end)=='OK');


end